"""empty message

Revision ID: d150f618dfd9
Revises: 
Create Date: 2021-06-04 14:39:25.475350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd150f618dfd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintopicstable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicname', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_topic_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topicsref', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_topic_table')
    op.drop_table('maintopicstable')
    # ### end Alembic commands ###
